### ISSUE TITLE
.so files can be linked to the wrong version

### ISSUE THREAD

**Issue by calispac** [dneise/protozfitsreader#4]
I just reinstalled this package on my machine and doing so I encountered the following problem.
```python
(ctapipe) alispach@alispach-ThinkPad-X1-Carbon-4th:~/Documents/PhD/ctasoft$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import protozfitsreader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/__init__.py", line 6, in <module>
    from . import rawzfitsreader
ImportError: /home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/rawzfitsreader.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN4ACTL2IO13ProtobufIFitsC1ERKSsS3_PKN6google8protobuf10DescriptorE
>>> 
```
```
(ctapipe) alispach@alispach-ThinkPad-X1-Carbon-4th:~/Documents/PhD/ctasoft$ ldd ~/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/rawzfitsreader.cpython-35m-x86_64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x00007ffe76378000)
        libZFitsIO.so => /home/alispach/Documents/PhD/ctasoft/CamerasToACTL/trunk/Build.Release/lib/libZFitsIO.so (0x00007f2f50dfe000)
        libpython3.5m.so.1.0 => /home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/../../../libpython3.5m.so.1.0 (0x00007f2f5090b000)
        libstdc++.so.6 => /home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/../../../libstdc++.so.6 (0x00007f2f5054f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2f50246000)
        libgcc_s.so.1 => /home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader/../../../libgcc_s.so.1 (0x00007f2f5002f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2f4fe12000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2f4fa48000)
        libACTLCore.so => /home/alispach/Documents/PhD/ctasoft/CamerasToACTL/trunk/Build.Release/lib/libACTLCore.so (0x00007f2f4f7bd000)
        libz.so.1 => /home/alispach/.anaconda3/envs/ctapipe/lib/libz.so.1 (0x00007f2f4f5a7000)
        libprotobuf.so.9 => /usr/local/lib/libprotobuf.so.9 (0x00007f2f4f296000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2f4f092000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2f4ee8f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2f4ec87000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2f51291000)
        libzmq.so.5 => /home/alispach/.anaconda3/envs/ctapipe/lib/libzmq.so.5 (0x00007f2f4ea24000)

```

I believe my issue is here because it uses an older version of `libZitsIO.so` and `libACTLCore.so` even if they are in `/home/alispach/.anaconda3/envs/ctapipe/lib/python3.5/site-packages/protozfitsreader`.
Is there a way to avoid that rather than removing the old `.so` files?

**Comment by dneise** [comment]
I am no expert for (dynamic) linking, but I've seen that the linker looks in:
1. LD_LIBRARY_PATH
2. RPATH (defined in the .so file header)
3. Default paths, like /usr/lib or so.

When the RPATH is an absolute path **and** the LD_LIB_PATH is empty, then I understand there is little chance to accindentally link wrong versions.

If the user defines the LD_LIB_PATH to point to 'wrong' versions of some dependencies, then the dynamic linker has no other choice but to use exactly these 'wrong' versions.

Therefore my first question: Is the variable LD_LIBRARY_PATH set on the machine you are using? And does the problem persist, when you *unset* this variable?

---

Since the author of the so-file does not know where the user will put the so-file in the end, an absolute RPATH is impossible (at least I undstand it this way).

So a relative RPATH was set: $ORIGIN, which simply means: “hey linker, look for dependencies in the same folder where you have found this so file.“

Since some so files have multiple dependencies, multiple RPATHs were defined:
 - $ORIGIN, i.e. “right here“ and
 - $ORIGIN/../../.., i.e. “3 folders up from here“.

If by pure bad luck the correct version of a dependency is “right here“ and the wrong version is “3 folders up from here“. Then I think we have to take closer look at the *order* in the RPATH.

**Comment by calispac** [comment]
You are correct. I just had from previous installation `LD_LIBRARY_PATH` with an the old folder where it was looking for the wrong .so file.

Unfortunately I cannot retest it since I just removed entirely this folder. 
Anyhow it should not affect new users. Thanks !
